export const ROUTES = {
  home: '/',
  auth: '/auth',
  authAdminLogin: '/auth/admin/login',
  authOwnerLogin: '/auth/owner/login',
  authClientLogin: '/auth/client/login',
  authClientRegister: '/auth/client/register',
  guestSearch: '/search',
  guestCheckout: '/checkout',
  clientDashboard: '/client-dashboard',
  adminDashboard: '/dashboard',
  adminCrm: '/crm',
  adminBookings: '/bookings',
  adminUnits: '/units',
  adminAreas: '/areas',
  adminClients: '/clients',
  adminOwners: '/owners',
  adminFinance: '/finance',
  adminReviews: '/reviews',
  adminSettings: '/settings',
  ownerDashboard: '/owner-dashboard',
  ownerUnits: '/owner-units',
  ownerBookings: '/owner-bookings',
  ownerCalendar: '/owner-calendar',
  ownerEarnings: '/owner-earnings',
  ownerNotifications: '/owner-notifications',
} as const;